# https://www.roole.fr/application-roole-map

server=/api.onesignal.com/
server=/decision.flagship.io/
server=/events.flagship.io/
server=/api.mixpanel.com/
server=/api-eu.mixpanel.com/
server=/api-js.mixpanel.com/
server=/firebaseinstallations.googleapis.com/
server=/firebase-settings.crashlytics.com/
server=/firebaseremoteconfigrealtime.googleapis.com/
server=/firebaselogging-pa.googleapis.com/
server=/crashlyticsreports-pa.googleapis.com/
server=/app-analytics-services.com/
#server=/ca.iadsdk.apple.com/
server=/iadsdk.apple.com/

