# https://www.whatsapp.com

server=/iphone-crashlog.whatsapp.net/
server=/crashlogs.whatsapp.net/
# ???
server=/privatestats.whatsapp.net/
# https://api.whatsapp.net/falco/pigeon_health_metrics
server=/api.whatsapp.net/
# https://graph.whatsapp.net/logging_client_events
server=/graph.whatsapp.net/
server=/dit.whatsapp.net/

